
# configs:
#   basketItems_file:
#     file: ./conf/basketItems.json
#   clerks_file:
#     file: ./conf/clerks.json
#   stores_file:
#     file: ./conf/stores.json

# watch 'docker exec shadowtraffic curl -s localhost:9400/metrics |grep events_sent'
services:

  shadowtraffic:
    image: shadowtraffic/shadowtraffic:latest
    container_name: shadowtraffic
    hostname: shadowtraffic
    volumes:
      - ./conf:/workspace
    entrypoint: ["java", "-jar", "/home/shadowtraffic.jar"]
    command: ["--config", "/workspace/avro-retail.json"]
    env_file:
      - conf/license.env
      - conf/params.env
    # configs:
    #   - source: basketItems_file
    #     target: /workspace/basketItems.json
    #     mode: 444
    #   - source: clerks_file
    #     target: /workspace/clerks.json
    #     mode: 444
    #   - source: stores_file
    #     target: /workspace/stores.json
    #     mode: 444